### ISSUE TITLE
idl_cpu_pm incompatable with IDL 8.7.2

### ISSUE THREAD

**Issue by wogallery** [bernatp3rs/idl_cpu_pm#1]
When compiling idl_cpu_pm\xidl_idlbridge__define.pro, idl 8.7.2 gives the error:
_____________________________________________________
Compiled module: XIDL_IDLBRIDGE::CALL_BATCH.

    key_info=self->processkey(n_extra,_ref_extra=extra)
                                                       ^
% Keyword _REF_EXTRA is not allowed when calling a routine.
  At: D:\Idl\Workbench_01\wgallery_dev2\software\libs\external\idl_cpu_pm\xidl_idlbridge__define.pro, Line 162
% 1 Compilation error(s) in module XIDL_IDLBRIDGE::PROCESSROUTINE.
% Compiled module: XIDL_IDLBRIDGE::PROCESSVAR.
_____________________________________________________
 Changing the line:
 key_info=self->processkey(n_extra,_ref_extra=extra)
to:
 key_info=self->processkey(n_extra, _extra=extra)
removes the compile error.
Apparently the original is in error: the keyword '_ref_extra' is not allowed in the call to a routine, only in the called routine's declaration. However, idl 8.5.2 does not flag the error and my programs using it run fine.

If I make the correction, some of my programs in idl 8.7.2 run fine but others fail. So far I have not been able to debug this.

William Gallery
wgallery@battelleecology.org

**Comment by bernatp3rs** [comment]
The error has been fixed!
